//! Expiry model, duration validation, and boot-time expiry semantics.
//!
//! `Expiry` is deliberately a struct variant on `At` (`At { epoch: u64 }`),
//! not a tuple variant (`At(u64)`). Under serde's internally-tagged
//! representation (`#[serde(tag = "kind")]`), a tuple newtype variant has no
//! map to inject the tag into and fails at serialization time, not at build
//! time. The struct variant moves that guarantee into the type system (see
//! design.md Architecture Decisions).

use serde::{Deserialize, Serialize};

/// Minimum accepted duration, in seconds, for a temporary `--until` grant.
pub const MIN_DURATION_SECS: u64 = 60;
/// Maximum accepted duration, in seconds, for a temporary `--until` grant.
pub const MAX_DURATION_SECS: u64 = 28_800;

/// Expiry policy for a NoPass grant: permanent, revoked at next reboot, or a
/// fixed UTC epoch.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "lowercase")]
pub enum Expiry {
    Never,
    Reboot,
    At { epoch: u64 },
}

impl Expiry {
    /// True only for `At { epoch }` with `epoch <= now`. `Never` and
    /// `Reboot` are never expired by this check — `expire --uid` must not
    /// delete a rule whose header is `never`, `reboot`, or a still-future
    /// epoch.
    pub fn is_expired(&self, now: u64) -> bool {
        matches!(self, Expiry::At { epoch } if *epoch <= now)
    }

    /// Like [`Expiry::is_expired`], but `Reboot` also counts as expired —
    /// used only by the boot-time cleanup sweep.
    pub fn is_expired_at_boot(&self, now: u64) -> bool {
        match self {
            Expiry::Reboot => true,
            Expiry::At { epoch } => *epoch <= now,
            Expiry::Never => false,
        }
    }
}

/// Every way a candidate `--until` duration can fail validation.
#[derive(Debug, Clone, Copy, PartialEq, Eq, thiserror::Error)]
pub enum DurationError {
    #[error("until is not in the future")]
    NotInFuture,
    #[error("duration {secs}s is below the {MIN_DURATION_SECS}s minimum")]
    TooShort { secs: u64 },
    #[error("duration {secs}s exceeds the {MAX_DURATION_SECS}s maximum")]
    TooLong { secs: u64 },
}

/// Validates that `until` is strictly in the future of `now` and that the
/// resulting duration falls within `[MIN_DURATION_SECS, MAX_DURATION_SECS]`
/// inclusive. Returns the validated duration in seconds.
pub fn validate_until(now: u64, until: u64) -> Result<u64, DurationError> {
    if until <= now {
        return Err(DurationError::NotInFuture);
    }
    let secs = until - now;
    if secs < MIN_DURATION_SECS {
        return Err(DurationError::TooShort { secs });
    }
    if secs > MAX_DURATION_SECS {
        return Err(DurationError::TooLong { secs });
    }
    Ok(secs)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::header;
    use crate::template::render_rule;

    #[test]
    fn each_expiry_form_round_trips_through_render_and_parse() {
        for expiry in [Expiry::Never, Expiry::Reboot, Expiry::At { epoch: 1_789_000_000 }] {
            let rendered = render_rule(1000, "jorge", expiry);
            let parsed = header::parse(&rendered).unwrap();
            assert_eq!(parsed.expires, expiry);
        }
    }

    #[test]
    fn expiry_serializes_as_internally_tagged_json() {
        let json = serde_json::to_string(&Expiry::At { epoch: 1_789_000_000 }).unwrap();
        assert_eq!(json, r#"{"kind":"at","epoch":1789000000}"#);
        let round_tripped: Expiry = serde_json::from_str(&json).unwrap();
        assert_eq!(round_tripped, Expiry::At { epoch: 1_789_000_000 });
    }

    #[test]
    fn unrecognized_header_value_is_a_typed_error_not_a_silent_default() {
        let content = "# Generated by NoPass — do not edit manually\n\
            # nopass-user: jorge\n\
            # nopass-expires: soon\n";
        let err = header::parse(content).unwrap_err();
        assert_eq!(err, header::HeaderError::MalformedExpires);
    }

    #[test]
    fn validate_until_accepts_the_minimum_and_maximum_boundary() {
        let now = 1_000_000;
        assert_eq!(validate_until(now, now + MIN_DURATION_SECS), Ok(MIN_DURATION_SECS));
        assert_eq!(validate_until(now, now + MAX_DURATION_SECS), Ok(MAX_DURATION_SECS));
    }

    #[test]
    fn validate_until_rejects_one_second_below_the_minimum() {
        let now = 1_000_000;
        assert_eq!(
            validate_until(now, now + MIN_DURATION_SECS - 1),
            Err(DurationError::TooShort { secs: MIN_DURATION_SECS - 1 })
        );
    }

    #[test]
    fn validate_until_rejects_one_second_above_the_maximum() {
        let now = 1_000_000;
        assert_eq!(
            validate_until(now, now + MAX_DURATION_SECS + 1),
            Err(DurationError::TooLong { secs: MAX_DURATION_SECS + 1 })
        );
    }

    #[test]
    fn validate_until_rejects_a_value_in_the_past() {
        let now = 1_000_000;
        assert_eq!(validate_until(now, now - 1), Err(DurationError::NotInFuture));
    }

    #[test]
    fn validate_until_rejects_a_value_equal_to_now() {
        let now = 1_000_000;
        assert_eq!(validate_until(now, now), Err(DurationError::NotInFuture));
    }

    #[test]
    fn is_expired_true_only_for_past_or_present_at_epoch() {
        assert!(Expiry::At { epoch: 100 }.is_expired(100));
        assert!(Expiry::At { epoch: 100 }.is_expired(200));
        assert!(!Expiry::At { epoch: 100 }.is_expired(50));
        assert!(!Expiry::Never.is_expired(u64::MAX));
        assert!(!Expiry::Reboot.is_expired(u64::MAX));
    }

    #[test]
    fn is_expired_at_boot_treats_reboot_as_expired() {
        assert!(Expiry::Reboot.is_expired_at_boot(0));
        assert!(Expiry::At { epoch: 100 }.is_expired_at_boot(200));
        assert!(!Expiry::At { epoch: 100 }.is_expired_at_boot(50));
        assert!(!Expiry::Never.is_expired_at_boot(u64::MAX));
    }
}
