//! Rule-file header grammar: banner / `nopass-user` / `nopass-expires`.
//!
//! Hand-parsed with `strip_prefix` and char-class predicates, deliberately
//! not the `regex` crate (see design.md Architecture Decisions) — the
//! grammar is fixed and closed, so four anchored prefix checks are simpler
//! and lighter than pulling `regex-automata`/`aho-corasick`/`memchr` into a
//! privileged binary.

use crate::expiry::Expiry;
use crate::template::{BANNER, MAX_USERNAME_LEN};

const USER_PREFIX: &str = "# nopass-user: ";
const EXPIRES_PREFIX: &str = "# nopass-expires: ";

/// The parsed banner/user/expires portion of a rule file.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RuleHeader {
    pub user: String,
    pub expires: Expiry,
}

/// Every way the fixed three-line header can fail to parse.
#[derive(Debug, Clone, Copy, PartialEq, Eq, thiserror::Error)]
pub enum HeaderError {
    #[error("first line is not the NoPass banner")]
    MissingBanner,
    #[error("second line is not a `# nopass-user:` line")]
    MissingUser,
    #[error("third line is not a `# nopass-expires:` line")]
    MissingExpires,
    #[error("nopass-user value does not match [A-Za-z0-9._-]{{1,32}}")]
    MalformedUser,
    #[error("nopass-expires value is not `never`, `reboot`, or a valid epoch")]
    MalformedExpires,
}

/// Parses the fixed banner/user/expires header from rule-file `content`.
/// Only the first three lines are consulted; the fourth (`#<uid> ALL=...`)
/// line is not required for a header to parse.
pub fn parse(content: &str) -> Result<RuleHeader, HeaderError> {
    let mut lines = content.lines();

    let banner = lines.next().ok_or(HeaderError::MissingBanner)?;
    if banner != BANNER {
        return Err(HeaderError::MissingBanner);
    }

    let user_line = lines.next().ok_or(HeaderError::MissingUser)?;
    let user_raw = user_line.strip_prefix(USER_PREFIX).ok_or(HeaderError::MissingUser)?;
    if user_raw.is_empty() || user_raw.chars().count() > MAX_USERNAME_LEN || !user_raw.chars().all(is_user_char) {
        return Err(HeaderError::MalformedUser);
    }

    let expires_line = lines.next().ok_or(HeaderError::MissingExpires)?;
    let expires_raw = expires_line
        .strip_prefix(EXPIRES_PREFIX)
        .ok_or(HeaderError::MissingExpires)?;
    let expires = parse_expires(expires_raw).ok_or(HeaderError::MalformedExpires)?;

    Ok(RuleHeader {
        user: user_raw.to_string(),
        expires,
    })
}

/// True when `content` carries a valid NoPass banner, user line, and
/// expires line — the ownership test used before any delete.
pub fn is_nopass_owned(content: &str) -> bool {
    parse(content).is_ok()
}

fn is_user_char(c: char) -> bool {
    c.is_ascii_alphanumeric() || matches!(c, '.' | '_' | '-')
}

/// Grammar: `never | reboot | 0 | [1-9][0-9]{0,18}`.
fn parse_expires(raw: &str) -> Option<Expiry> {
    match raw {
        "never" => return Some(Expiry::Never),
        "reboot" => return Some(Expiry::Reboot),
        "0" => return Some(Expiry::At { epoch: 0 }),
        _ => {}
    }
    let mut chars = raw.chars();
    let first = chars.next()?;
    if !first.is_ascii_digit() || first == '0' {
        return None;
    }
    let rest = &raw[first.len_utf8()..];
    if rest.len() > 18 || !rest.chars().all(|c| c.is_ascii_digit()) {
        return None;
    }
    raw.parse::<u64>().ok().map(|epoch| Expiry::At { epoch })
}

#[cfg(test)]
mod tests {
    use crate::expiry::Expiry;
    use crate::header::{is_nopass_owned, parse, HeaderError};

    const VALID: &str = "# Generated by NoPass — do not edit manually\n\
        # nopass-user: jorge\n\
        # nopass-expires: 1789000000\n\
        #1000 ALL=(ALL) NOPASSWD: ALL\n";

    #[test]
    fn parses_valid_header_into_ruleheader() {
        let header = parse(VALID).unwrap();
        assert_eq!(header.user, "jorge");
        assert_eq!(header.expires, Expiry::At { epoch: 1_789_000_000 });
    }

    #[test]
    fn parses_never_and_reboot_expires() {
        let never = "# Generated by NoPass — do not edit manually\n\
            # nopass-user: jorge\n\
            # nopass-expires: never\n\
            #1000 ALL=(ALL) NOPASSWD: ALL\n";
        assert_eq!(parse(never).unwrap().expires, Expiry::Never);

        let reboot = "# Generated by NoPass — do not edit manually\n\
            # nopass-user: jorge\n\
            # nopass-expires: reboot\n\
            #1000 ALL=(ALL) NOPASSWD: ALL\n";
        assert_eq!(parse(reboot).unwrap().expires, Expiry::Reboot);
    }

    #[test]
    fn missing_banner_is_rejected() {
        let content = "# some other file\n# nopass-user: jorge\n# nopass-expires: never\n";
        assert_eq!(parse(content).unwrap_err(), HeaderError::MissingBanner);
    }

    #[test]
    fn missing_user_line_is_rejected() {
        let content = "# Generated by NoPass — do not edit manually\n";
        assert_eq!(parse(content).unwrap_err(), HeaderError::MissingUser);
    }

    #[test]
    fn malformed_user_line_is_rejected() {
        let content = "# Generated by NoPass — do not edit manually\n\
            # nopass-user: \n\
            # nopass-expires: never\n";
        assert_eq!(parse(content).unwrap_err(), HeaderError::MalformedUser);
    }

    #[test]
    fn missing_expires_line_is_rejected() {
        let content = "# Generated by NoPass — do not edit manually\n\
            # nopass-user: jorge\n";
        assert_eq!(parse(content).unwrap_err(), HeaderError::MissingExpires);
    }

    #[test]
    fn unrecognized_expires_value_is_rejected_with_typed_error() {
        let content = "# Generated by NoPass — do not edit manually\n\
            # nopass-user: jorge\n\
            # nopass-expires: soon\n";
        assert_eq!(parse(content).unwrap_err(), HeaderError::MalformedExpires);
    }

    #[test]
    fn is_nopass_owned_true_for_valid_content() {
        assert!(is_nopass_owned(VALID));
    }

    #[test]
    fn is_nopass_owned_false_for_foreign_content() {
        assert!(!is_nopass_owned("# some other sudoers fragment\nfoo ALL=(ALL) ALL\n"));
    }
}
