//! Fixed-format rule-file rendering and username sanitization.
//!
//! `render_rule` is the only place a username can reach the on-disk rule
//! file; it always sanitizes before interpolating, so an unsanitized value
//! can never leak through this function even if a caller forgets to
//! pre-sanitize.

use crate::expiry::Expiry;

/// The fixed banner line that anchors NoPass ownership detection. It MUST be
/// reproduced byte-for-byte everywhere it appears; the em dash is U+2014.
pub const BANNER: &str = "# Generated by NoPass — do not edit manually";

/// Maximum length of a sanitized username, matching the header grammar's
/// `[A-Za-z0-9._-]{1,32}` capture. Crate-internal and shared with `header`
/// so the rendering side and the parsing side can never drift apart.
pub(crate) const MAX_USERNAME_LEN: usize = 32;

/// Drops every character outside `[A-Za-z0-9._-]`, truncates to 32
/// characters, and falls back to `"unknown"` when the result is empty.
pub fn sanitize_username(raw: &str) -> String {
    let sanitized: String = raw
        .chars()
        .filter(|c| c.is_ascii_alphanumeric() || matches!(c, '.' | '_' | '-'))
        .take(MAX_USERNAME_LEN)
        .collect();
    if sanitized.is_empty() {
        "unknown".to_string()
    } else {
        sanitized
    }
}

/// Renders the fixed four-line rule file content for `uid`/`user`/`expires`.
/// `user` is sanitized internally, so callers never need to pre-sanitize.
pub fn render_rule(uid: u32, user: &str, expires: Expiry) -> String {
    let user = sanitize_username(user);
    let expires = match expires {
        Expiry::Never => "never".to_string(),
        Expiry::Reboot => "reboot".to_string(),
        Expiry::At { epoch } => epoch.to_string(),
    };
    format!(
        "{BANNER}\n# nopass-user: {user}\n# nopass-expires: {expires}\n#{uid} ALL=(ALL) NOPASSWD: ALL\n"
    )
}

#[cfg(test)]
mod tests {
    use crate::expiry::Expiry;
    use crate::template::{render_rule, sanitize_username};

    #[test]
    fn renders_fixed_format_for_at_expiry() {
        let rendered = render_rule(1000, "jorge", Expiry::At { epoch: 1_789_000_000 });
        assert_eq!(
            rendered,
            "# Generated by NoPass — do not edit manually\n\
             # nopass-user: jorge\n\
             # nopass-expires: 1789000000\n\
             #1000 ALL=(ALL) NOPASSWD: ALL\n"
        );
    }

    #[test]
    fn renders_never_and_reboot_expires_lines() {
        assert!(render_rule(1000, "jorge", Expiry::Never).contains("# nopass-expires: never\n"));
        assert!(render_rule(1000, "jorge", Expiry::Reboot).contains("# nopass-expires: reboot\n"));
    }

    #[test]
    fn sanitize_username_preserves_dotted_name_verbatim() {
        assert_eq!(sanitize_username("ana.perez"), "ana.perez");
    }

    #[test]
    fn sanitize_username_strips_space_containing_name() {
        assert_eq!(sanitize_username("john doe"), "johndoe");
    }

    #[test]
    fn sanitize_username_strips_shell_metacharacters() {
        assert_eq!(sanitize_username("a;b|c&d$e`f"), "abcdef");
    }

    #[test]
    fn render_rule_never_interpolates_unsanitized_username() {
        let rendered = render_rule(1000, "a;rm -rf /", Expiry::Never);
        assert!(rendered.contains("# nopass-user: arm-rf\n"));
        assert!(!rendered.contains(';'));
        assert!(!rendered.contains('|'));
    }

    // The cases below pin the threat matrix's "External command composition"
    // username leg. The implementation is an allowlist, so these hold today;
    // they exist so a future rewrite into a denylist fails loudly instead of
    // silently reopening the hole.

    #[test]
    fn sanitize_username_strips_line_terminators() {
        // The worst case: a surviving newline would append an attacker-chosen
        // line to a sudoers file.
        assert_eq!(sanitize_username("root\nevil"), "rootevil");
        assert_eq!(sanitize_username("root\r\nevil"), "rootevil");
        assert_eq!(sanitize_username("root\u{0085}evil"), "rootevil");
        assert_eq!(sanitize_username("root\u{2028}evil"), "rootevil");
    }

    #[test]
    fn render_rule_cannot_gain_a_line_from_the_username() {
        let rendered = render_rule(1000, "root\r\n# nopass-user: evil", Expiry::Never);
        assert_eq!(rendered.lines().count(), 4);
        assert!(rendered.contains("# nopass-user: rootnopass-userevil\n"));
        assert!(!rendered.contains('\r'));
    }

    #[test]
    fn sanitize_username_strips_nul_quotes_and_backslash() {
        assert_eq!(sanitize_username("a\0b'c\"d\\e"), "abcde");
        assert_eq!(sanitize_username("100%s"), "100s");
    }

    #[test]
    fn sanitize_username_strips_non_ascii_and_bidi_overrides() {
        assert_eq!(sanitize_username("josé"), "jos");
        assert_eq!(sanitize_username("ab\u{202e}cd"), "abcd");
    }

    #[test]
    fn sanitize_username_falls_back_when_nothing_survives() {
        assert_eq!(sanitize_username(""), "unknown");
        assert_eq!(sanitize_username(";|&$`"), "unknown");
        assert_eq!(sanitize_username("日本語"), "unknown");
    }

    #[test]
    fn sanitize_username_truncates_to_the_grammar_maximum() {
        let long = "a".repeat(100);
        let out = sanitize_username(&long);
        assert_eq!(out.chars().count(), super::MAX_USERNAME_LEN);
        assert_eq!(out, "a".repeat(32));
    }

    #[test]
    fn sanitize_username_truncates_after_filtering_not_before() {
        // 40 dropped characters followed by 5 kept ones: truncation must see
        // the filtered stream, or the result would be empty.
        let raw = format!("{}{}", " ".repeat(40), "jorge");
        assert_eq!(sanitize_username(&raw), "jorge");
    }
}
